### ISSUE TITLE
Does not specify Python version trove classifiers

### ISSUE THREAD

**Issue by danpalmer** [graingert/elaphe#5]
This project is being highlighted by `https://caniusepython3.com/` as not being compatible with Python 3 as it does not have the Python 3 trove classifier.

**Comment by graingert** [comment]
caniusepython3 should read setup.cfg, or check the wheels on PyPI

```
[bdist_wheel]
universal=1
```

**Comment by danpalmer** [comment]
It doesn't, and this should still have the correct trove classifiers.

**Comment by graingert** [comment]
@danpalmer PRs welcome!
